### ISSUE TITLE
用的nacos，sentinel版本可以提供下么，兼容不太好这两个中间件

### ISSUE THREAD

**Issue by liufeiguo** [DreamChan/fast-cloud#1]

**Comment by liufeiguo** [comment]
而且fast-cloud-system启动有错误，Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available

**Comment by liufeiguo** [comment]
No qualifying bean of type 'cn.dreamchan.system.service.mapstruct.DeptMapStruct' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by DreamChan** [comment]
nacos: 1.3.0
sentinel: 1.7.2
项目用到了Mapstruct 这个工具，你需要编译下代码的后检测’target/generated-sources‘这个目录下是否有实现类生成

**Comment by liufeiguo** [comment]
好的，我这边编译一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DreamChan/fast-cloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 上午9:57
收件人:&nbsp;"DreamChan/fast-cloud"<fast-cloud@noreply.github.com&gt;;
抄送:&nbsp;"ip139施亮"<771474065@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DreamChan/fast-cloud] 用的nacos，sentinel版本可以提供下么，兼容不太好这两个中间件 (#1)





 
nacos: 1.3.0
 sentinel: 1.7.2
 上面的错误是用到了Mapstruct 这个工具，你需要编译下代码的后检测’target/generated-sources‘这个目录下是否有实现类生成
