### ISSUE TITLE
dev-api/auth/oauth/token这个接口本地测试正常，部署到其他机器就没有权限了。请问是什么原因？

### ISSUE THREAD

**Issue by CizChenzhoU** [DreamChan/fast-cloud#2]
Status Code: 401 Unauthorized

**Comment by DreamChan** [comment]
不知道你实际是怎样部署的，你可以考虑下：1.部署时是否修改前端工程的配置文件；2.是否是跨域引起的

**Comment by DreamChan** [comment]
不知道你实际是怎样部署的，你可以考虑下：1.部署时是否修改前端工程的配置文件；2.是否是跨域引起的

**Comment by DreamChan** [comment]
@CizChenzhoU 不知道你实际是怎样部署的，你可以考虑下：1.部署时是否修改前端工程的配置文件；2.是否是跨域引起的

**Comment by CizChenzhoU** [comment]
感谢回答
前端在本地启动就没改，这个不用更改吧
equest URL: http://localhost:5000/dev-api/auth/oauth/token?username=admin&password=123456&code=4397&uuid=9cf7fc37-c7f9-4319-9ff7-b7dd7c97ecbf&client_id=fastcloud&client_secret=123456&grant_type=password&scope=server
Request Method: POST
Status Code: 401 Unauthorized
Remote Address: 127.0.0.1:5000
Referrer Policy: strict-origin-when-cross-origin

**Comment by DreamChan** [comment]
@CizChenzhoU  如果你是前端部署在本地，后台接口部署到其他机器上，你需要把vue.config.js 文件中的 devServer配置target地址修改成后端接口部署的机器ip、端口

**Comment by CizChenzhoU** [comment]
太感谢了！


因为这个前端我没有用elm采用的是vueifly所有没有用直接你的前端。


造成了一些坑。


再次感谢你的及时回答。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DreamChan/fast-cloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 上午10:45
收件人:&nbsp;"DreamChan/fast-cloud"<fast-cloud@noreply.github.com&gt;;
抄送:&nbsp;"一百里天"<523897704@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [DreamChan/fast-cloud] dev-api/auth/oauth/token这个接口本地测试正常，部署到其他机器就没有权限了。请问是什么原因？ (#2)





 
@CizChenzhoU  如果你是前端部署在本地，后台接口部署到其他机器上，你需要把vue.config.js 文件中的 devServer配置target地址修改成后端接口部署的机器ip、端口
