### ISSUE TITLE
后台登录成功卡在HikariPool-1 - Starting...（本地测试正常。部署其他设备出现。数据库为同一数据）

### ISSUE THREAD

**Issue by CizChenzhoU** [DreamChan/fast-cloud#3]
![image](https://user-images.githubusercontent.com/12556302/102464529-6689c680-4087-11eb-9839-82afa8ab8fcc.png)
![image](https://user-images.githubusercontent.com/12556302/102464700-a781db00-4087-11eb-8023-1b54723c4597.png)

**Comment by DreamChan** [comment]
@CizChenzhoU 请详细描述下前后端部署情况

**Comment by CizChenzhoU** [comment]
后端所有接口部署在另外一台电脑上面

打包maven
clean install -Dmaven.test.skip=true -pl auth -am -Pdev

nacos单独部分在另外一台机器。
![image](https://user-images.githubusercontent.com/12556302/102472105-ecf6d600-4090-11eb-8872-8880fc548686.png)

前端本地启动接口改成部署的地址

前几天我以为是前端问题，不过后来发现不是。

查了几天没什么头绪

**Comment by DreamChan** [comment]
@CizChenzhoU 根据你的描述我部署了测试下，没有出现你描述的问题。

**Comment by CizChenzhoU** [comment]
@DreamChan 谢谢答复。目前已解决。
原因为mysql-connector-java版本过高，之前引入的是8.0
把版本降到5.1 更换 com.mysql.jdbc.Driver 问题解决
之前一直没想到这个问题原因是本机测试和部署到其他机器测试都是连接同一数据库。

更换后程序正常。只是造成的原因还是不太明白。
可能是和我自动打包工具有关~
